### DISCUSSION TITLE
Investigation into version tags in dependents

### DISCUSSION THREAD

**Discussion by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#23] [General]
> > I wouldn't mind splitting out functionality for newer versions, but SemVer is not properly followed for many GitHub Actions, so maintaining backwards compatibility is a necessity
> 
> Hmmm... I have had different experiences. Most actions always have explicit v1 or vN tags, especially in the examples that people copy paste. All of the https://github.com/actions do this, as do all of the https://github.com/wow-actions. In fact, you _can't_ just do `actions/checkout`, you are forced to do `actions/checkout@v3` or if you're really risky, `@main`.
> 
> 🔬👨‍🔬 I think this needed more investigation and research before we define a path forward. Cause, yeah, I have seen some that do `@main` in their examples. I don't know how widespread it is among the 163 dependants that we have. 🤷‍♂️

&mdash; https://github.com/Andrew-Chen-Wang/github-wiki-action/issues/18#issuecomment-1464749440

**Comment by jcbhmr** [comment]
- [x] Todo @jcbhmr: search the most recent top 10 in https://github.com/Andrew-Chen-Wang/github-wiki-action/network/dependents and report what pin they are using (main vs v3 vs v2)
- [x] Todo @jcbhmr: search the OLDEST top 10 in https://github.com/Andrew-Chen-Wang/github-wiki-action/network/dependents and report what pin they are using
- [ ] Todo @jcbhmr: look through a few middle ones and see https://github.com/Andrew-Chen-Wang/github-wiki-action/network/dependents

**Reply by jcbhmr** [reply]
Number that use "v3" as a tag: 23
Number that use "master" as a tag: 0 -- none that I could find! 🎉
Number that use a commit id: 6
Number that use "v2": 26

<details>
<summary>First page of https://github.com/Andrew-Chen-Wang/github-wiki-action/network/dependents as of 03/12/2023</summary>

jarneamerlinck / python-sphinx-documentation
doesn't use action

robbrad / UKBinCollectionData
uses v3
```yml
    - name: Deploy Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure WIKI_DIR ends with / as action uses rsync
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "generate_wiki.py"
```

erv123 / ShadertoyMC
doesn't use action

kevingrillet / Py-ForzaHorizon5-Tools
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync
          WIKI_DIR: .wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.GH_MAIL }}
          GH_NAME: ${{ github.repository_owner }}
```

Kirbitz / NomicGameManager.Api
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: documentation/
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
```

filiptibell / lune
uses v3
```yml
      - name: Push wiki changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_GITHUB_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
```

CommunalHelper / CommunalHelper
uses v3
```yml
    - name: Sync Wiki
      if: ${{ !fromJSON(env.PRERELEASE) }}
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: github-actions@github.com
        GH_NAME: ${{ github.repository_owner }}
```

CaptCardoso / Afrobeats-Recommender-System
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki
        WIKI_DIR: wiki
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.cardosoafolabi@yahoo.com }}
        GH_NAME: ${{ github.Afolabi Cardoso }}
        EXCLUDED_FILES: "a/ b.md"
```

AbdullahAlfaraj / Auto-Photoshop-StableDiffusion-Plugin
doesn't actually use action

Imaginary-Horizons-Productions / HorizonsBot
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.WIKI }}
          GH_MAIL: ${{ secrets.WIKI_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "a/ b.md"
```

LeoDog896 / JointMMO
uses v2
```yml
      - name: Sync Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: docs/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ github.triggering_actor }}
          GH_NAME: ${{ github.repository_owner }}
```

CodeZwei / ex-bgio
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ github.event.pusher.email }}
        GH_NAME: ${{ github.event.pusher.name }}
```

3s-urriza / rewards-booster
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ github.event.pusher.email }}
        GH_NAME: ${{ github.event.pusher.name }}
```

abhijoshi2k / recent-activity
uses v2
```yml
    - name: Updating Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GH_NAME: 'github-actions[bot]'
        EXCLUDED_FILES: 'README.md'
        WIKI_PUSH_MESSAGE: '${{ github.event.commits[0].message }}'
```

wr-projects / ospo
uses commit id
```yml
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@194d37ff03f5220e1baf7eb9d7c7ad7f3e1db30c
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}
```

wr-projects / monorepojs-scaffolding
uses commit id
```yml
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@194d37ff03f5220e1baf7eb9d7c7ad7f3e1db30c
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}
```

wr-projects / github-jstemplate
uses commit id
```yml
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@194d37ff03f5220e1baf7eb9d7c7ad7f3e1db30c
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}
```

wr-projects / github-template
uses commit id
```yml
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@194d37ff03f5220e1baf7eb9d7c7ad7f3e1db30c
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}
```

RenanTelles / ExemploJenkinsDotNet
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

PINTO0309 / onnx2tf
uses commit id
```yml
    - name: Update wiki content
      uses: Andrew-Chen-Wang/github-wiki-action@7f44b142379b209235c748351558937d3e7546a7
      continue-on-error: true
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_NAME: ${{ secrets.GH_REPO_OWNER }}
        GH_MAIL: ${{ secrets.GH_EMAIL }}
        EXCLUDED_FILES: "test_model_pb/"
```

actions-marketplace-validations / Readme-Workflows_recent-activity
uses v3
```yml
    - name: Updating Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GH_NAME: 'github-actions[bot]'
        EXCLUDED_FILES: 'README.md'
        WIKI_PUSH_MESSAGE: '${{ github.event.commits[0].message }}'
```

AlexTuisov / delete_decomposition
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync
        # WIKI_DIR's default is wiki/
        WIKI_DIR: docs/wiki/
        GH_TOKEN: ${{ secrets.WIKI_GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.WIKI_COMMITTER_EMAIL }}
        GH_NAME: ${{ secrets.WIKI_COMMITTER_NAME }}
```

pabllopf / Alis
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync 
          # WIKI_DIR's default is wiki/
          WIKI_DIR: docs/wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.GH_MAIL }}
          GH_NAME: ${{ github.repository_owner }}
          #EXCLUDED_FILES: "a/ b.md"
```

Watano-Page / page_models
doesn't use action

senseiwells / EssentialClient
uses v3
```yml
      - name: Update Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: docs/wiki/
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GH_MAIL: senseiwells@users.noreply.github.com
          GH_NAME: senseiwells
```

201flaviosilva-labs / utilidades
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: wiki/ # WIKI_DIR's default is wiki/ - Make sure you have that / at the end. We use rsync
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ github.event.pusher.email }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "_ignore/"
```

dibble-james / LinQL
uses v3
```yml
      - name: Sync Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        if: github.ref_type == 'tag'
        env:
          WIKI_DIR: docs/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: 11923585+dibble-james@users.noreply.github.com
          GH_NAME: ${{ github.repository_owner }}
```

uikilin100 / onnx-tensorflow
uses v2
```yml
    - name: Update wiki content
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure WIKI_DIR ends with '/' and matches the checkout path above
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # These are used for the wiki commit author and push credentials.
        # Username must have push rights to wiki repository.
        GH_NAME: ${{ github.event.pusher.name }}
        GH_MAIL: ${{ github.event.pusher.email }}
```

hollow-cube / common
uses v2
```yml
      - name: Sync Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: docs/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ github.triggering_actor }}
          GH_NAME: ${{ github.repository_owner }}
```

Shawnice / sphinx-example
doesn't use action

</details>

<details>
<summary>Last page of https://github.com/Andrew-Chen-Wang/github-wiki-action/network/dependents?dependents_after=MTkxMzA4MDYzNTk as of 03/12/2023</summary>


MrOctopus / nl_cmd
uses v2
```yml
    - name: Push wiki changes
      if: success()
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        EXCLUDED_FILES: "ski_configbase.md"
        WIKI_DIR: ./nl_cmd/wiki/
        GH_TOKEN: ${{ github.token }}
        GH_MAIL: ${{ secrets.NL_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        WIKI_PUSH_MESSAGE: "Updated wiki"
```

kevingrillet / AFKArena-LabHelper
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync
        WIKI_DIR: .wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.GH_MAIL }}
        GH_NAME: ${{ github.repository_owner }}
```

juliankeppler / sweproject
uses v2
```yml
    - name: Update Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: "julian@juliankeppler.de"
        GH_NAME: github_actions
```

hfingler / ava
uses v2
```yml
    - name: Upload README Notes to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
        GH_MAIL:  ${{ secrets.GH_AVA_EMAIL }}
        GH_NAME:  ${{ github.repository_owner }}
```

aelfa / trash-updater
uses v2
```yml
      - name: Upload Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.PAT }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "*.json"
```

anjuna-security / ava
uses v2
```yml
    - name: Upload README Notes to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
        GH_MAIL:  ${{ secrets.GH_AVA_EMAIL }}
        GH_NAME:  ${{ github.repository_owner }}
```

mworzala / canary
uses v2
```yml
      - name: Sync Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: docs/
          GH_TOKEN: ${{ secrets.PAT }}
          GH_MAIL: ${{ secrets.COMMIT_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
```

Vultik / ESP3D
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

Pheelix / ESP3D
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

aiplan4eu / unified-planning
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync
        # WIKI_DIR's default is wiki/
        WIKI_DIR: docs/wiki/
        GH_TOKEN: ${{ secrets.WIKI_GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.WIKI_COMMITTER_EMAIL }}
        GH_NAME: ${{ secrets.WIKI_COMMITTER_NAME }}
```

MrOctopus / nl_mcm
uses v3
```yml
    - name: Push wiki changes
      if: success()
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: ./nl_mcm/wiki/
        GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        GH_MAIL: ${{ secrets.NL_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        WIKI_PUSH_MESSAGE: "Updated wiki"
```

avulic / TestWeb
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: ./doc/
        GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        GH_MAIL: antevulic96@gmail.com
        GH_NAME: ${{ github.repository_owner }}
```

ansible-community / github-docs-build
uses commit id
```yml
      - name: Publish docs
        if: fromJSON(env.SHOULD_RUN)
        # @v3 https://github.com/Andrew-Chen-Wang/github-wiki-action/releases/tag/v3
        uses: Andrew-Chen-Wang/github-wiki-action@194d37ff03f5220e1baf7eb9d7c7ad7f3e1db30c
        env:  # this action is written such that the inputs must be specified as env vars
          # WIKI_DIR is going to be used with rsync, it MUST end in a forward slash [/]
          WIKI_DIR: ${{ env.WIKI }}/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ github.event.head_commit.author.email }}
          # GH_NAME is going to be used raw in a URL in an unquoted commandline, it can't contain spaces
          # it's supposed to be a username, not a name, but it doesn't need to be a valid username,
          # at least not with GITHUB_TOKEN (for a PAT, may need to match, unsure)
          GH_NAME: ${{ github.event.head_commit.author.username || github.repository.owner }}[bot]
          WIKI_PUSH_MESSAGE: 'Docs for ${{ github.repository }}/${{ github.event.head_commit.id }} : ${{ github.event.head_commit.message }}'
```

Foxies-CSTL / ESP3D
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

oh-hell / ESP3D
not used

hounslg / ESP3D
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

wowmua / Maps
uses v2
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          # Make sure you have that / at the end. We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: .github/wiki/
          GH_TOKEN: ${{ secrets.WIKI_TOKEN }}
          GH_MAIL: ${{ secrets.OWNER_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "a/ b.md"
```

ShohninDmitriy / ESP3D
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

MMichotte / SLG_APP
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: "martin.michotte@gmail.com"
        GH_NAME: "MMichotte"
```

photoszzt / ava
uses v2
```yml
    - name: Upload README Notes to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
        GH_MAIL:  ${{ secrets.GH_AVA_EMAIL }}
        GH_NAME:  ${{ github.repository_owner }}
```

Andrew-Chen-Wang / natural-gravity-engine
uses v2
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.ANDREW_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "circle.py"
```

yuhc / ava
uses v2
```yml
    - name: Upload README Notes to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
        GH_MAIL:  ${{ secrets.GH_AVA_EMAIL }}
        GH_NAME:  ${{ github.repository_owner }}
```

bradendubois / do-calculus
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
```

sl1pkn07 / ESP3D
uses v3
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

zebscripts / AFK-Daily
uses v3
```yml
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: _wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.OWNER_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
```

utcs-scea / ava
uses v2
```yml
    - name: Upload README Notes to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
        GH_MAIL:  ${{ secrets.GH_AVA_EMAIL }}
        GH_NAME:  ${{ github.repository_owner }}
```

bradendubois / competitive-programming
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
```

luc-github / ESP32SSDP
uses v2
```yml
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.MY_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
```

Readme-Workflows / recent-activity
uses v3
```yml
    - name: Updating Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GH_NAME: 'github-actions[bot]'
        EXCLUDED_FILES: 'README.md'
        WIKI_PUSH_MESSAGE: '${{ github.event.commits[0].message }}'
```

Rakambda / FallingTree
uses v3
```yml
      - name: Push changes to the wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: actions@github.com
          GH_NAME: github-actions[bot]
```

</details>
