### ISSUE TITLE
Access Denied error

### ISSUE THREAD

**Issue by AZMCode** [Andrew-Chen-Wang/github-wiki-action#1]
Hello, I have been trying to set up a workflow, using this action as such:

```
- name: Publish Docs to Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      with:
        WIKI_DIR: $GITHUB_WORKSPACE/docs/Markdown/ 
      env:
        # Directory to rsync files to the wiki.
        WIKI_DIR: $GITHUB_WORKSPACE/docs/Markdown/
        # The GitHub Token for this action to use. Specify secrets.GITHUB_TOKEN.
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: adrianozambrana@protonmail.com
        GH_NAME: ${{ github.repository_owner }}
        REPO: ${{ github.repository }}
```

and even though I gave the action proper auth, and the repository has a wiki (Not initialized yet), when ran it yields the following:
![Screenshot at 2020-07-30 21-26-32](https://user-images.githubusercontent.com/15837568/88990265-8290f500-d2ab-11ea-9613-0a4173e952cb.png)

Edit: It appears not init'ing the wiki before using the action results in failure. Perhaps a future feature of the action could include taking care of init'ing the wiki before push? In any way, closing this now.
