### ISSUE TITLE
Possible to automagically use ${{ github.token }} ?

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#17]
Currently:

![image](https://user-images.githubusercontent.com/61068799/223893074-97b0a814-6e5a-45bb-8ba9-14fcad9201d7.png)

https://github.com/Andrew-Chen-Wang/github-wiki-action/blob/7f44b142379b209235c748351558937d3e7546a7/action.yml#L10-L16

But, I think you can make it magic so you don't need to specify the GH_TOKEN variable:

```yml
  GH_TOKEN:
    description: 'The GitHub Token for this action to use. Specify secrets.GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
    # 🔺
```

I don't know 100% for sure, but I _think_ this is possible. I think it's at least worth investigating though.

Here's what I know does work: https://github.com/jcbhmr/publish-wiki-action/blob/a9cd93ca56fd5ed2bf562abc26af3771fb8e63bd/action.yml
```yml
runs:
  using: composite
  steps:
    - id: gh-action
      run: '"${GITHUB_ACTION_PATH%/}/index.sh"'
      shell: bash
      # https://github.com/actions/runner/issues/665
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_PATH: ${{ inputs.path }}
```

**Comment by Andrew-Chen-Wang** [comment]
That is pretty interesting, and honestly pretty surprising security wise. Without specified user input of a GitHub token, public repositories (from first glance) are at risk of write vulnerabilities from a third party library/action. Does the above code actually permit pushing without the GitHub action yml file specifying token?

**Comment by jcbhmr** [comment]
> That is pretty interesting, and honestly pretty surprising security wise. Without specified user input of a GitHub token, public repositories (from first glance) are at risk of write vulnerabilities from a third party library/action

I think they _were_ until the default got switched to read-only https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

> Does the above code actually permit pushing without the GitHub action yml file specifying token?

This workflow works!

```yml
name: Test
on:
  push:
    paths: [index.sh, action.yml, wiki/**, .github/workflows/test.yml]
concurrency: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./
```

https://github.com/jcbhmr/publish-wiki-action/blob/a9cd93ca56fd5ed2bf562abc26af3771fb8e63bd/.github/workflows/test.yml

I don't think that it would work if I created a new repo today since the default is `contents: read` not `contents: write` (see Changelog blog https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/)

![image](https://user-images.githubusercontent.com/61068799/224256495-b9b8dec9-d7ce-4bdd-950b-38a5594f398b.png)

Yeah so that repo has inherited the default read-write and I _could_ change it if I wanted

**Comment by Andrew-Chen-Wang** [comment]
I think doing this implicitly is not great practice, so closing. Feel free to add more comments.

**Comment by jcbhmr** [comment]
> I think doing this implicitly is not great practice, so closing.

To play advocate for the other side, here's some reasons why doing this:

```yml
- uses: actions/checkout@v3 # doesn't need GH_TOKEN to pull from repo
- uses: Andrew-Chen-Wang/github-wiki-action # to conform with others, it'd be nice to have default pick it up
- uses: actions/deploy-pages@v1 # picks up token to deploy a website
- uses: stefanzweifel/git-auto-commit-action@v4 # literally pushes to the repo with one line, no token
```

is preferable to the verbosity of this:

```yml
- uses: actions/checkout@v3
  with:
    token: ${{ github.token }}
- uses: Andrew-Chen-Wang/github-wiki-action
  with:
    GH_TOKEN: ${{ github.token }}
- uses: actions/deploy-pages@v1
  with:
    token: ${{ github.token }}
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    token: ${{ github.token }}
```

note that you **STILL NEED TO DECLARE PERMISSIONS** to give that token access to writing the pages, repo, issues, whatever: https://github.com/actions/deploy-pages

```yml
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
```
