### ISSUE TITLE
Use with inputs instead of env

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#27]
Right now we use this:

```yml
- uses: Andrew-Chen-Wang/github-wiki-action@v3
  env:
    GH_TOKEN: ...
```

Ideally, we should use the `with:` inputs block instead

```yml
- uses: Andrew-Chen-Wang/github-wiki-action@v3
  with:
    token: ...
```
