### ISSUE TITLE
Auto update vX tags when vX.Y.Z releases are made

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#39]
ref #30 

Added an update-tags.yml action to auto-create v4 tags from v4.0.0 releases and keep them always updated. There's an official action for this! When you release a vX.Y.Z tag it changes vX to point to it.

https://github.com/Andrew-Chen-Wang/github-wiki-action/blob/jcbhmr/.github/workflows/update-tags.yml

official usage from https://github.com/actions/deploy-pages/blob/main/.github/workflows/release.yml

```yml
name: Release
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    environment:
      # Note: this environment is protected
      name: Release
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        id: update-major-tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ env.TAG_NAME }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
```
