### ISSUE TITLE
Add wiki_url output

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#56]
https://github.com/actions/deploy-pages has a `outputs.page_url` output that is very nice when used like:

```yml
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
```

I think this is a good idea to add to the current action as a non-breaking v4.2 feature

@Andrew-Chen-Wang thoughts? I want a second opinion.

@Andrew-Chen-Wang btw if you missed it I released v4.1: https://github.com/Andrew-Chen-Wang/github-wiki-action/releases/tag/v4.1.0 because it ADDED A NON-BREAKING FEATURE to do debug logging #54 😊
