### ISSUE TITLE
Does not rename README to Home

### ISSUE THREAD

**Issue by Jomik** [Andrew-Chen-Wang/github-wiki-action#77]
I have just enabled this action and moved my wiki into a `wiki/` directory.
![image](https://github.com/user-attachments/assets/ef1d2ad4-d629-49a2-a9dd-f3b2117c2ded)
After running the action, it looks like this 
![image](https://github.com/user-attachments/assets/64fe93a6-587f-49b3-a2c4-a2c08d976bf0)
This is my workflow
```yml
name: Publish wiki
on:
  push:
    # branches: [main]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
```
